"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
command_timeout = 1000
format = """
$sudo\
$username\
$directory\
$git_branch\
$git_status\
$fill\
$bun\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$time\n \
$character\
"""
palette = "rose-pine"

[palettes.rose-pine]
  foam    = '#9ccfd8'
  gold    = '#f6c177'
  iris    = '#c4a7e7'
  love    = '#eb6f92'
  overlay = '#26233a'
  pine    = '#31748f'
  rose    = '#ebbcba'

[profiles]
  transient = "$sudo$username$fill$time\n $character"

[sudo]
  disabled = false
  format   = "[î‚¶](fg:overlay)[ $symbol ]($style)[î‚´](fg:overlay) "
  style    = "bg:overlay fg:iris"
  symbol   = "î·«"

[character]
  format = "[ó±ª](fg:iris) "

[directory]
  format            = "[î‚¶](fg:overlay)[ $path ]($style)[î‚´](fg:overlay) "
  style             = "bg:overlay fg:pine"
  truncation_length = 3
  truncation_symbol = "â€¦/"

  [directory.substitutions]
    Blender   = " î¦ "
    Documents = " ó°ˆ™ "
    Downloads = " ï€™ "
    Godot     = " î™Ÿ "
    Java      = " îœ¸ "
    Minecraft = " ó°³ "
    Music     = " ï€ "
    Pictures  = " ï€¾ "
    Projects  = " î»¿ "
    Python    = " îœ¼ "
    Rust      = " î¨ "
    Web       = " îœ¶ "

[fill]
  style  = "fg:overlay"
  symbol = "="

[git_branch]
  format = "[î‚¶](fg:overlay)[ $symbol $branch ]($style)[î‚´](fg:overlay) "
  style  = "bg:overlay fg:foam"
  symbol = "ï˜"

[git_status]
  ahead      = '[â‡¡\(${count}\)](bg:overlay fg:foam)'
  behind     = '[â‡£\(${count}\)](bg:overlay fg:rose)'
  deleted    = '[âœ˜\($count\)](style)'
  disabled   = false
  diverged   = 'â‡•[\[](bg:overlay fg:iris)[â‡¡\(${ahead_count}\)](bg:overlay fg:foam)[â‡£\(${behind_count}\)](bg:overlay fg:rose)[\]](bg:overlay fg:iris)'
  format     = '[î‚¶](fg:overlay)([$all_status$ahead_behind]($style))[î‚´](fg:overlay) '
  modified   = '[!\($count\)](bg:overlay fg:gold)'
  renamed    = '[Â»\($count\)](bg:overlay fg:iris)'
  staged     = '[++\($count\)](bg:overlay fg:gold)'
  stashed    = '[\$](bg:overlay fg:iris)'
  style      = "bg:overlay fg:love"
  untracked  = '[?\($count\)](bg:overlay fg:gold)'
  up_to_date = '[ âœ“ ](bg:overlay fg:iris)'

[time]
  disabled    = false
  format      = " [î‚¶](fg:overlay)[ $time ó°´ˆ ]($style)[î‚´](fg:overlay)"
  style       = "bg:overlay fg:rose"
  time_format = "%I:%M%P"
  use_12hr    = false

[username]
  disabled    = false
  format      = "[î‚¶](fg:overlay)[ ó°§± $user ]($style)[î‚´](fg:overlay) "
  show_always = true
  style_root  = "bg:overlay fg:iris"
  style_user  = "bg:overlay fg:iris"

  # Languages

[bun]
  disabled = false
  format   = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
  style    = "bg:overlay fg:pine"
  symbol   = "î¯ "

[c]
  disabled = false
  format   = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
  style    = "bg:overlay fg:pine"
  symbol   = "î˜ "

[elixir]
  disabled = false
  format   = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
  style    = "bg:overlay fg:pine"
  symbol   = "î‰µ "

[elm]
  disabled = false
  format   = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
  style    = "bg:overlay fg:pine"
  symbol   = "î˜¬ "

[golang]
  disabled = false
  format   = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
  style    = "bg:overlay fg:pine"
  symbol   = "î˜§ "

[haskell]
  disabled = false
  format   = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
  style    = "bg:overlay fg:pine"
  symbol   = "î· "

[java]
  disabled = false
  format   = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
  style    = "bg:overlay fg:pine"
  symbol   = "î‰– "

[julia]
  disabled = false
  format   = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
  style    = "bg:overlay fg:pine"
  symbol   = "î˜¤ "

[nodejs]
  disabled = false
  format   = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
  style    = "bg:overlay fg:pine"
  symbol   = "ó°™ "

[nim]
  disabled = false
  format   = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
  style    = "bg:overlay fg:pine"
  symbol   = "ó°†¥ "

[rust]
  disabled = false
  format   = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
  style    = "bg:overlay fg:pine"
  symbol   = "î¨ "

[scala]
  disabled = false
  format   = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
  style    = "bg:overlay fg:pine"
  symbol   = "îœ· "

[python]
  disabled = false
  format   = " [î‚¶](fg:overlay)[ $symbol$version ]($style)[î‚´](fg:overlay)"
  style    = "bg:overlay fg:pine"
  symbol   = 'îœ¼ '

[conda]
  disabled = false
  format   = " [î‚¶](fg:overlay)[ $symbol$environment ]($style)[î‚´](fg:overlay)"
  style    = "bg:overlay fg:pine"
  symbol   = 'ğŸ…’ '
